### ISSUE TITLE
A big jump in the file size

### ISSUE THREAD

**Issue by ZahraMousavi** [asmecher/hypothesis#16]
Hi there. I don't know if it's an issue, but I noticed a big jump in the file size from hypothesis-v1.0.2-0.tar.gz
 (14.8 KB) to hypothesis-v1.0.3-2.tar.gz (3.88 GB). Since our server has an upload file size limitation, I would like to know if it is a bug or we should change our file size limitations?

**Comment by asmecher** [comment]
@ZahraMousavi, that's 3.88MB, not 3.88GB, correct?

The new release of the plugin includes a pdf.js implementation that's compatible with Hypothes.is, which make the plugin quite a bit bigger. I'd suggest increasing the file size limit. (If you're working with PDF files, they'll often be bigger than 5MB anyway.)

Note that the Plugin Gallery is the best place to get/install plugins, and it won't require you to upload the plugin yourself. It takes care of compatibility checks.

Our support forum is the best place for Q&A -- see https://forum.pkp.sfu.ca/ for details.
