### ISSUE TITLE
Plugin fails to load in on abralin.org after OJS update

### ISSUE THREAD

**Issue by chrisshaw** [asmecher/hypothesis#19]
Hi @asmecher! Thanks a ton for contributing this plugin to the Hypothesis and OJS communities :pray: 

We had a user report the plugin is failing to load after updating to a new version of OJS. I've summarized the important details from https://github.com/hypothesis/product-backlog/issues/1285 below:

---

Notes from the user (he points to your video):

The steps for the Hypothesis plugin integration is described here:  https://youtu.be/Xm4_tkIy9QI. The plugin is still available in the list of plugins of OJS. In the case of our journal, it is enabled, as the print below indicate:

![image](https://user-images.githubusercontent.com/22603275/136065019-dd3f4dcc-699f-436c-8347-0d2db49c5623.png)

However, when users open the PDF file in the webpage, Hypothesis won't function. You can try it here: https://cadernos.abralin.org/index.php/cadernos/article/view/271.

_The following will not play in Safari_

https://user-images.githubusercontent.com/2966918/152854855-a1f33774-1c3c-448e-8bc8-2a6da15ae32a.mp4

---

While we don't have the capacity to maintain your project, we're currently featuring you in our [integration gallery](https://web.hypothes.is/tools-plug-ins-and-integrations/) and we'd be happy to support you via our [Open Slack](https://web.hypothes.is/help/how-can-i-get-access-to-the-code-or-talk-to-hypothesis-developers/). Our lead developers often hang out there to answer questions from the broader community. You can also submit issues to the appropriate [repo](https://github.com/hypothesis) should you encounter any problems.

**Comment by asmecher** [comment]
@chrisshaw, check `plugins/generic/hypothesis/README` in your installation for notes on PDF support. Note that newer versions of OJS (and the Hypothes.is plugin) don't require this additional step.
