### ISSUE TITLE
Support for XML galleys?

### ISSUE THREAD

**Issue by unkej** [asmecher/hypothesis#20]
Hi @asmecher 

is there a way to modify the plugin that it works with XML galleys and the eLife Lens Article Viewer, too?

Kind regards
jens

**Comment by asmecher** [comment]
@unkej, the support forum (https://pkp.sfu.ca) is the best place to ask questions like this -- but no, not currently. That would require a modification to Lens Reader similar to the one that Hypothesis maintains for PDF.js (see https://github.com/hypothesis/pdf.js-hypothes.is for that repository). Our Hypothesis plugin simply integrates the third-party tools; the tools themselves would need to support this first.
